server:
  port: 8080

zillow:
  rapidapi:
    host: zillow-com1.p.rapidapi.com
    key: ${RAPIDAPI_KEY}

googleapi31:
  rapidapi:
    host: google-api31.p.rapidapi.com
    key: ${RAPIDAPI_KEY}
  endpoint: https://google-api31.p.rapidapi.com/map